In [5]:
import collections
import pandas as pd
#imports

In [6]:
with open('test.txt', 'r') as info:
  count = collections.Counter(info.read())
  print(count.items())

dict_items([('\n', 1), ('a', 3), ('w', 4), ('s', 5), ('e', 5), ('r', 3), ('d', 7), ('t', 3), ('f', 13), ('g', 16), ('y', 4), ('b', 10), ('h', 14), ('u', 3), ('n', 8), ('j', 9), ('i', 2), ('m', 6), ('k', 6), ('1', 3), ('2', 6), ('3', 8), ('4', 8), ('5', 8), ('6', 9), ('7', 10), ('8', 9), ('9', 7), ('0', 5), ('z', 2), ('x', 3), ('c', 4), ('v', 8), (',', 3), ('l', 2), ('-', 2), ('.', 2), ('/', 3), ("'", 3), (']', 4), ('A', 2), ('Z', 3), ('S', 2), ('X', 1), ('D', 1), ('C', 1), ('F', 1), ('V', 1), ('G', 1), (' ', 5), ('\\', 1), ('[', 2), ('P', 1), ('O', 1), ('I', 1), ('J', 1), ('U', 1), ('=', 1), ('`', 1), (';', 1)])

In [7]:
#final_df = pd.DataFrame(count)
df = pd.DataFrame.from_dict(count, orient='index').reset_index()
df

   index   0
0     \n   1
1      a   3
2      w   4
3      s   5
4      e   5
5      r   3
6      d   7
7      t   3
8      f  13
9      g  16
10     y   4
11     b  10
12     h  14
13     u   3
14     n   8
15     j   9
16     i   2
17     m   6
18     k   6
19     1   3
20     2   6
21     3   8
22     4   8
23     5   8
24     6   9
25     7  10
26     8   9
27     9   7
28     0   5
29     z   2
30     x   3
31     c   4
32     v   8
33     ,   3
34     l   2
35     -   2
36     .   2
37     /   3
38     '   3
39     ]   4
40     A   2
41     Z   3
42     S   2
43     X   1
44     D   1
45     C   1
46     F   1
47     V   1
48     G   1
49         5
50     \   1
51     [   2
52     P   1
53     O   1
54     I   1
55     J   1
56     U   1
57     =   1
58     `   1
59     ;   1

In [8]:
df = df.rename(columns={'index':'Characters', 0:'Occurance'})
#df['Column'] = df['Column'].astype(float)
df['Occurance %']=df['Occurance']
df['Occurance %']=df['Occurance %'].astype(float)
x=df['Occurance'].sum ()
print(df['Occurance'].sum ())
for i in df.axes[0]:
 df['Occurance %'][i]=df['Occurance'][i]/x
df

260

<ipython-input-8-ccef9b08adf8>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Occurance %'][i]=df['Occurance'][i]/x

   Characters  Occurance  Occurance %
0          \n          1     0.003846
1           a          3     0.011538
2           w          4     0.015385
3           s          5     0.019231
4           e          5     0.019231
5           r          3     0.011538
6           d          7     0.026923
7           t          3     0.011538
8           f         13     0.050000
9           g         16     0.061538
10          y          4     0.015385
11          b         10     0.038462
12          h         14     0.053846
13          u          3     0.011538
14          n          8     0.030769
15          j          9     0.034615
16          i          2     0.007692
17          m          6     0.023077
18          k          6     0.023077
19          1          3     0.011538
20          2          6     0.023077
21          3          8     0.030769
22          4          8     0.030769
23          5          8     0.030769
24          6          9     0.034615
25          7         10     0.038462
26          8          9     0.034615
27          9          7     0.026923
28          0          5     0.019231
29          z          2     0.007692
30          x          3     0.011538
31          c          4     0.015385
32          v          8     0.030769
33          ,          3     0.011538
34          l          2     0.007692
35          -          2     0.007692
36          .          2     0.007692
37          /          3     0.011538
38          '          3     0.011538
39          ]          4     0.015385
40          A          2     0.007692
41          Z          3     0.011538
42          S          2     0.007692
43          X          1     0.003846
44          D          1     0.003846
45          C          1     0.003846
46          F          1     0.003846
47          V          1     0.003846
48          G          1     0.003846
49                     5     0.019231
50          \          1     0.003846
51          [          2     0.007692
52          P          1     0.003846
53          O          1     0.003846
54          I          1     0.003846
55          J          1     0.003846
56          U          1     0.003846
57          =          1     0.003846
58          `          1     0.003846
59          ;          1     0.003846

In [9]:
df.to_csv('out.csv')